name = "backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"
account_id = "cb08ee7e11f68fade1c303c525e8da0f"


# D1 Database binding: connects remote Cloudflare D1 to env.DB in your Worker code
[[d1_databases]]
binding = "DB"
database_name = "omrundrapackersandmovers_db"
database_id = "8dd40380-0c28-40a2-84ea-647391c7cdef"
migrations_dir = "drizzle"

# Public environment variables (non-sensitive)
[vars]
ENVIRONMENT = "production"
BREVO_SENDER_EMAIL = "hello@1stompackersandmovers.com"
BREVO_SENDER_NAME = "Om Rudra Packers and Movers"
NOTIFICATION_EMAIL = "hello@1stompackersandmovers.com"

# Observability (Logs & Traces)
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true
