import { useState } from "react";
import { useParams, useLocation, Link, Navigate } from "react-router";
import { ArrowRight, ChevronRight, MapPin, PhoneCall, Plus, Minus, Check } from "lucide-react";
import { allRoutes } from "../../../../data/locations";
import { getLocationPageData, locationPath, locationAddress } from "../../../../data/locations/pageData";
import { company } from "../../../../data/company";
import { responsiveImageSet } from "../../../../utils/responsiveImages";
import SEO from "../../../../configs/seo";
import NotFound from "../../shared/components/NotFound";
import CustomSelect from "../../shared/components/CustomSelect";
import LocationAutocomplete from "../Home/components/LocationAutocomplete";

const services = [
  { name: "Home shifting", slug: "home-shifting", image: "home-shifting-v2.webp", text: "Discuss furniture, appliances and cartons, along with the packing and handling your home needs." },
  { name: "Office shifting", slug: "office-commercial-shifting", image: "office-commercial-shifting-v2.webp", text: "Share your equipment, workplace inventory and access arrangements to discuss a moving schedule." },
  { name: "Car transport", slug: "car-transportation", image: "car-transportation-v2.webp", text: "Check transport arrangements for your car, including handover documents and condition records." },
  { name: "Bike transport", slug: "bike-transportation", image: "bike-transportation-v2.webp", text: "Discuss packing and transport for your bike, with handover documents and a record of its condition." },
];
const domain = "https://omrudrapackersandmovers.com";
export default function LocationPage() {
  const { slug: rawSlug } = useParams();
  const { pathname } = useLocation();
  const slug = (rawSlug || "").replace(/^packers-movers-/, "");
  const route = allRoutes.find(item => item.slug === slug);
  if (route) return <Navigate to={`/route/${route.slug}`} replace />;
  const data = getLocationPageData(slug);
  if (!data) return <NotFound />;
  const canonical = locationPath(data.location);
  if (pathname !== canonical) return <Navigate to={canonical} replace />;
  return <LocationContent key={slug} data={data} />;
}
function LocationContent({ data }) {
  const { location, parent, label, kind, guide, listedAreas, routes, sameState, checklist, faqs } = data;
  const [destination, setDestination] = useState("");
  const [service, setService] = useState("Home shifting");
  const [areaQuery, setAreaQuery] = useState("");
  const [error, setError] = useState("");
  const pickup = locationAddress(location);
  const quote = (to = "", selectedService = service) => `/get-quote?${new URLSearchParams({ from: pickup, to, service: services.find(item => item.name === selectedService)?.slug || "home-shifting" })}`;
  const canonical = `${domain}${locationPath(location)}`;
  const areas = listedAreas.filter(item => item.name.toLowerCase().includes(areaQuery.trim().toLowerCase()));
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "Service", "@id": `${canonical}#service`, name: `Moving enquiries for ${location.name}`, serviceType: "Moving services", areaServed: { "@type": "Place", name: `${location.name}, ${location.state}` }, provider: { "@type": "Organization", name: company.legalName, url: domain }, url: canonical },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: domain }, { "@type": "ListItem", position: 2, name: "Where We Serve", item: `${domain}/where-we-serve` }, { "@type": "ListItem", position: 3, name: location.name, item: canonical }] },
  ] };
  return <>
    <SEO title={`Packers and Movers in ${location.name}`} description={`Plan a move in ${location.name}, ${location.state}. Review ${kind === "area" ? "local address access" : "pickup details"}${routes.length ? ` and ${routes.length} listed city routes` : " and service options"}, then request a quote with your location prefilled.`} canonical={canonical} schemaJson={schema} />
    <section className="bg-surface border-b border-border py-8 sm:py-12"><div className="container mx-auto px-4 sm:px-6"><nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-2 text-xs sm:text-sm text-text-muted mb-7"><Link to="/">Home</Link><ChevronRight size={14} /><Link to="/where-we-serve">Where We Serve</Link><ChevronRight size={14} /><span aria-current="page">{location.name}</span></nav>
      <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,1.2fr)_minmax(0,1fr)] gap-8 lg:gap-14 items-start"><div className="min-w-0"><p className="text-primary font-semibold text-sm">{parent ? `${parent.name.toUpperCase()} LOCAL AREA` : location.state.toUpperCase()} · MOVING WITH YOU</p><h1 className="font-display font-bold text-4xl sm:text-5xl leading-tight mt-4">Packers and movers<br />in <span className="text-primary">{label}.</span></h1><p className="text-text-muted text-base sm:text-lg leading-relaxed mt-5">{guide ? guide.intro : kind === "area" ? `From your doorstep in ${label} to your next address, start with a plan for packing, pickup and delivery. Tell us where in ${parent?.name || location.city} you are moving.` : kind === "district" ? `Moving within ${label} or heading to another city? Share your exact town or neighbourhood in ${location.state}, your destination and the belongings you want to bring.` : `A new home in ${label}, an office move or a journey to another city. Share your addresses in ${location.state} and beyond so our team can discuss the details with you.`}</p><ul className="text-sm space-y-3 mt-6">{["Quote based on your route and inventory", "Packing, handling and access discussed together", "No payment to send an enquiry"].map(text => <li key={text} className="flex gap-2 items-start"><Check size={18} className="text-primary shrink-0" />{text}</li>)}</ul><a href={`tel:${company.phone.primary.replace(/[^+\d]/g, "")}`} className="inline-flex gap-2 items-center text-primary font-semibold min-h-11 mt-5"><PhoneCall size={17} />{company.phone.primaryDisplay}</a></div>
      <aside className="min-w-0 bg-background border border-border rounded-[var(--radius-lg)] p-5 sm:p-7"><h2 className="font-display font-bold text-2xl">Where will {label} take you next?</h2><p className="text-sm text-text-muted mt-2">Choose your destination to start a location-specific enquiry.</p><div className="flex items-start gap-3 bg-brand-soft rounded-[var(--radius-md)] p-4 mt-5"><MapPin size={20} className="text-primary shrink-0 mt-1" /><div><p className="text-xs text-text-muted">Your pickup</p><p className="font-semibold text-sm mt-1">{pickup}</p></div></div><form noValidate onSubmit={event => { if (!destination.trim() || destination.trim().length < 2) { event.preventDefault(); setError("Enter a destination city or area."); document.getElementById("location-destination")?.focus(); } }} action="/get-quote" className="space-y-4 mt-5"><input type="hidden" name="from" value={pickup} /><input type="hidden" name="to" value={destination.trim()} /><input type="hidden" name="service" value={services.find(item => item.name === service)?.slug || "home-shifting"} /><LocationAutocomplete id="location-destination" label="Moving to" value={destination} onChange={value => { setDestination(value); setError(""); }} placeholder="Enter destination city or area" required error={error} /><CustomSelect id="location-service" label="What are you moving?" options={services.map(item => item.name)} value={service} onChange={setService} /><button type="submit" className="w-full inline-flex justify-center items-center gap-2 bg-primary text-white rounded-full px-5 py-3 font-semibold hover:bg-primary/90">Plan this move<ArrowRight size={18} /></button></form><p className="text-xs text-text-muted mt-4 leading-relaxed">Exact address access and service availability are confirmed by the team before booking.</p></aside>
      </div></div></section>
    <section className="container mx-auto px-4 sm:px-6 py-10 sm:py-16"><p className="text-primary text-sm font-semibold">PLAN YOUR {label.toUpperCase()} PICKUP</p><h2 className="font-display font-bold text-3xl sm:text-4xl mt-3">{guide?.heading || <>Start with the <span className="text-primary">right details.</span></>}</h2>{guide && <div className="max-w-3xl mt-5"><p className="text-text-muted leading-relaxed">{guide.fact}</p><p className="text-sm mt-3">Address reference: {guide.references.map(source => <a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer" className="text-primary underline">{source.label}</a>)}</p><p className="text-xs text-text-muted mt-2">Geographical references help identify addresses. Pickup access and service availability are assessed separately by our team.</p></div>}<div className="grid md:grid-cols-3 gap-6 mt-7">{checklist.map(item => <article key={item.title} className="border-t border-border pt-5"><h3 className="font-display font-bold text-xl">{item.title}</h3><p className="text-sm text-text-muted leading-relaxed mt-3">{item.detail}</p></article>)}</div></section>
    {listedAreas.length > 0 && <section className="bg-surface border-y border-border py-10 sm:py-14"><div className="container mx-auto px-4 sm:px-6"><div className="flex flex-col sm:flex-row justify-between gap-5 sm:items-end"><div><p className="text-primary font-semibold text-sm">LOCAL ADDRESS DETAILS</p><h2 className="font-display font-bold text-3xl mt-3">{parent ? `More areas in ${parent.name}` : `Find your area in ${location.name}`}</h2><p className="text-text-muted text-sm mt-3">Select an area, then share the complete address with the team.</p></div><input type="search" aria-label="Search local areas" placeholder="Search a local area" value={areaQuery} onChange={event => setAreaQuery(event.target.value)} className="bg-background border border-border px-4 py-3 text-sm sm:w-72 min-w-0" /></div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2 mt-6">{areas.map(item => <Link key={item.name} to={item.location ? locationPath(item.location) : `/get-quote?from=${encodeURIComponent(`${item.name}, ${parent?.name || location.name}, ${location.state}`)}`} className="bg-background border border-border rounded-[var(--radius-md)] p-3 text-sm flex justify-between items-center gap-2 hover:border-primary/40 hover:bg-brand-soft"><span>{item.name}</span><ArrowRight size={15} className="text-primary shrink-0" /></Link>)}</div>{!areas.length && <p className="text-sm text-text-muted mt-4">No matching area. Try another name or enter your full address in the enquiry.</p>}</div></section>}
    <section className="container mx-auto px-4 sm:px-6 py-10 sm:py-16"><h2 className="font-display font-bold text-3xl">Moving services for <span className="text-primary">{label}.</span></h2><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-5 mt-7">{services.map(({ name, slug, image, text }) => <article key={slug} className="border border-border rounded-[var(--radius-md)] overflow-hidden bg-background flex flex-col"><Link to={`/services/${slug}`} className="block bg-surface"><img src={`/images/services/${image}`} srcSet={responsiveImageSet(`/images/services/${image}`)} sizes="(min-width: 1280px) 25vw, (min-width: 640px) 50vw, 100vw" alt={name} loading="lazy" decoding="async" width="640" height="360" className="w-full aspect-[16/9] object-cover" /></Link><div className="p-5 sm:p-6 flex flex-col flex-1"><h3 className="font-display font-bold text-xl">{name}</h3><p className="text-sm text-text-muted leading-relaxed mt-3">{text}</p><Link to={quote("", name)} className="inline-flex gap-2 items-center text-primary font-semibold text-sm min-h-11 mt-auto pt-3">Enquire for {label}<ArrowRight size={16} /></Link><Link to={`/services/${slug}`} className="block text-sm text-text-muted underline">Read service details</Link></div></article>)}</div><div className="bg-brand-soft border border-primary/15 rounded-[var(--radius-lg)] p-6 sm:p-8 mt-8 flex flex-col sm:flex-row justify-between sm:items-center gap-5"><div><h3 className="font-display font-bold text-xl">What will your {label} move cost?</h3><p className="text-sm text-text-muted mt-2 leading-relaxed max-w-2xl">Inventory, packing, distance, access and dates affect your quote. Review the price guide, then confirm what your own move includes.</p></div><Link to="/pricing" className="inline-flex gap-2 items-center text-primary font-semibold shrink-0 min-h-11">See indicative prices<ArrowRight size={17} /></Link></div></section>
    {routes.length > 0 && <section className="bg-surface border-y border-border py-10 sm:py-14"><div className="container mx-auto px-4 sm:px-6"><p className="text-primary font-semibold text-sm">{parent ? `${parent.name.toUpperCase()} CITY CONNECTIONS` : "YOUR CITY CONNECTIONS"}</p><h2 className="font-display font-bold text-3xl mt-3">Routes involving <span className="text-primary">{parent?.name || location.name}.</span></h2><p className="text-text-muted text-sm mt-3">{parent ? `These are listed routes for ${parent.name}. Include your ${label} address when checking pickup arrangements.` : "Explore the listed routes, then confirm exact pickup, delivery and availability."}</p>{[{ heading: `Leaving ${parent?.name || location.name}`, items: routes.filter(route => route.fromSlug === (parent?.slug || location.slug)) }, { heading: `Arriving in ${parent?.name || location.name}`, items: routes.filter(route => route.toSlug === (parent?.slug || location.slug)) }].filter(group => group.items.length).map(group => <div key={group.heading} className="mt-7"><h3 className="font-display font-bold text-xl">{group.heading}</h3><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-4">{group.items.map(route => <Link key={route.slug} to={`/route/${route.slug}`} className="bg-background border border-border rounded-[var(--radius-md)] p-4 flex justify-between items-center gap-3 hover:border-primary/40"><span className="font-semibold text-sm">{route.from} <span className="text-primary">→</span> {route.to}</span><ArrowRight size={16} className="text-primary shrink-0" /></Link>)}</div></div>)}</div></section>}
    <section className="container mx-auto px-4 sm:px-6 py-10 sm:py-16"><h2 className="font-display font-bold text-3xl">Your {label} moving <span className="text-primary">questions.</span></h2><div className="mt-6">{faqs.map(item => <details key={item.q} className="group border-b border-border"><summary className="flex items-center justify-between gap-4 py-5 font-semibold cursor-pointer list-none [&::-webkit-details-marker]:hidden">{item.q}<span className="text-primary shrink-0"><Plus size={20} className="group-open:hidden" /><Minus size={20} className="hidden group-open:block" /></span></summary><p className="text-text-muted leading-relaxed pb-5 max-w-3xl">{item.a}</p></details>)}</div>
    {sameState.length > 0 && <div className="mt-9"><h3 className="font-semibold text-lg">Other listed locations in {location.state}</h3><p className="text-text-muted text-sm mt-2">Explore another city or district in the same state or region.</p><div className="flex flex-wrap gap-2 mt-4">{sameState.slice(0, 8).map(item => <Link key={item.slug} to={locationPath(item)} className="border border-border rounded-full px-4 py-2 text-sm hover:text-primary hover:bg-brand-soft">{item.name}</Link>)}</div><Link to="/where-we-serve" className="inline-flex gap-2 items-center text-primary font-semibold text-sm min-h-11 mt-3">Browse the complete directory<ArrowRight size={16} /></Link></div>}
    {parent && <Link to={locationPath(parent)} className="inline-flex gap-2 items-center text-primary font-semibold text-sm min-h-11 mt-4">Explore moving in {parent.name}<ArrowRight size={16} /></Link>}
    <div className="bg-text text-background rounded-[var(--radius-lg)] p-6 sm:p-9 mt-9 flex flex-col sm:flex-row justify-between sm:items-center gap-5"><div><h2 className="font-display font-bold text-2xl">Make your next move from {label}.</h2><p className="text-sm opacity-80 mt-2">Your address is ready. Tell us where you want to go.</p></div><Link to={quote(destination)} className="inline-flex gap-2 items-center bg-primary text-white rounded-full px-5 py-3 font-semibold shrink-0">Request a free quote<ArrowRight size={17} /></Link></div>
    </section>
  </>;
}
