import { useState } from "react";
import { Link } from "react-router";
import { ChevronRight, ArrowRight, Plus, Minus, Check, PhoneCall, Package, MapPin, Building2, CalendarDays } from "lucide-react";
import SEO from "../../../../configs/seo";
import { company } from "../../../../data/company";
import { estimatorOptions, localHouseholdRates, interstateCorridors, vehicleRates } from "../../../../data/pricing";
import CustomSelect from "../../shared/components/CustomSelect";

const scopes = [{ id: "local", label: "Within a city" }, { id: "interstate", label: "Between states" }];
const guides = [{ id: "local", label: "Local home moves" }, { id: "interstate", label: "Interstate routes" }, { id: "vehicle", label: "Vehicle transport" }];
const factors = [
  { icon: Package, title: "Inventory and packing", description: "The amount, size and type of goods, plus any fragile-item protection or special handling." },
  { icon: MapPin, title: "Route and transport", description: "Pickup and destination, distance, vehicle arrangements and delivery requirements." },
  { icon: Building2, title: "Access at each address", description: "Floors, stairs, lift availability, parking and the distance from your door to the vehicle." },
  { icon: CalendarDays, title: "Date and extra services", description: "Your preferred schedule, storage, unpacking, assembly and other services you request." },
];
const questions = [
  ["Is the estimate a final quote?", "No. These ranges are planning guides from our current pricing data. Your inventory, route, access and selected services can change the price. Confirm the final scope and quote with the team before booking."],
  ["Are packing and unloading included?", "This depends on your selected service and the proposed quote. Ask for packing materials, loading, unloading, unpacking and placement to be listed separately so you know what is included."],
  ["Are taxes and insurance included in these ranges?", "Confirm applicable taxes, insurance premiums and any other charges with the team. Do not assume they are included in an indicative range. Ask for a written breakdown before booking."],
  ["What if my inventory or moving date changes?", "Tell the team as soon as your requirements change. They can review availability, the service plan and any effect on the quote before you proceed."],
  ["When do I pay, and what are the cancellation terms?", "Confirm payment timing, any advance, cancellation conditions and refund terms directly with the team before making a booking. Request these details in writing."],
];
function serviceSlug(id) {
  return id === "car" ? "car-transportation" : id === "bike" ? "bike-transportation" : id === "office" ? "office-commercial-shifting" : "home-shifting";
}
export default function Pricing() {
  const [moveId, setMoveId] = useState("2bhk");
  const [scope, setScope] = useState("local");
  const [guide, setGuide] = useState("local");
  const selected = estimatorOptions.find((item) => item.id === moveId) || estimatorOptions[1];
  const quotePath = `/get-quote?service=${serviceSlug(selected.id)}&type=${selected.id}&scope=${scope}`;
  return (
    <>
      <SEO title="Moving Cost Estimates & Pricing Guide" description="Explore indicative home moving and vehicle transport rates. Estimate a planning range and request a quote based on your inventory, route and moving date." />
      <section className="bg-brand-soft/50 py-6 sm:py-10 lg:py-12 border-b border-border" aria-labelledby="pricing-heading"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <nav aria-label="Breadcrumb" className="mb-5"><ol className="flex items-center gap-2 text-sm text-text-muted"><li><Link to="/" className="inline-flex items-center min-h-11 hover:text-primary">Home</Link></li><li aria-hidden="true"><ChevronRight size={14} /></li><li aria-current="page">Pricing</li></ol></nav>
        <div className="grid lg:grid-cols-[1.1fr_1fr] gap-8 lg:gap-14 items-center"><div><p className="text-primary text-sm font-semibold mb-3">Plan your moving budget</p><h1 id="pricing-heading" className="font-display font-extrabold text-[clamp(2rem,4vw,3.5rem)] leading-[1.12] tracking-tight">Know the range.<br /><span className="text-primary">Plan the details.</span></h1><p className="text-base sm:text-lg text-text-muted leading-relaxed max-w-xl mt-5">Start with a planning estimate. Then get a quote shaped around your belongings, route and service requirements.</p><a href="#pricing-guides" className="inline-flex items-center gap-2 min-h-11 mt-5 text-primary text-sm font-semibold hover:underline">Explore rate guides<ArrowRight size={17} aria-hidden="true" /></a></div>
          <div className="rounded-lg border border-border bg-background p-5 sm:p-7 shadow-card" aria-labelledby="estimate-heading"><h2 id="estimate-heading" className="font-display font-bold text-xl mb-5">Get a planning estimate</h2><fieldset className="mb-5"><legend className="text-sm font-semibold mb-2">Where are you moving?</legend><div className="grid grid-cols-2 gap-2">{scopes.map((item) => <button type="button" key={item.id} aria-pressed={scope === item.id} onClick={() => setScope(item.id)} className={`min-h-12 px-3 rounded-md border text-sm font-semibold ${scope === item.id ? "border-primary bg-brand-soft text-primary" : "border-border text-text-muted hover:border-primary/40"}`}>{item.label}</button>)}</div></fieldset><CustomSelect id="pricing-move-size" label="What are you moving?" value={selected.label} onChange={(value) => setMoveId(estimatorOptions.find((item) => item.label === value).id)} options={estimatorOptions.map((item) => item.label)} placeholder="Choose your move size" /><div className="rounded-md bg-surface border border-border p-4 mt-5" aria-live="polite"><p className="text-xs font-semibold text-primary mb-2">Indicative {scope === "local" ? "local" : "interstate"} range</p><p className="font-display text-2xl sm:text-3xl font-bold tracking-tight">{scope === "local" ? selected.localPrice : selected.interstatePrice}</p><p className="text-xs text-text-muted leading-relaxed mt-2">A planning guide, not a confirmed quote. Inventory, access, route and extras can change the price.</p></div><Link to={quotePath} className="inline-flex items-center justify-center gap-2 min-h-12 w-full bg-accent hover:bg-primary text-white text-sm font-bold rounded-md mt-4">Request my moving quote<ArrowRight size={17} aria-hidden="true" /></Link><p className="text-xs text-text-muted text-center mt-3">Your move size and route type carry into the enquiry.</p></div>
        </div>
      </div></section>
      <section id="pricing-guides" className="py-12 sm:py-16 scroll-mt-5" aria-labelledby="rate-guides-heading"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><h2 id="rate-guides-heading" className="font-display font-bold text-2xl sm:text-3xl tracking-tight">Indicative rate guides</h2><p className="text-text-muted text-base mt-3 max-w-2xl">Use these ranges to plan. Confirm your exact inventory, included services, taxes and any additional charges with the team.</p><div className="flex gap-5 sm:gap-8 overflow-x-auto border-b border-border mt-6 mb-7" aria-label="Choose a pricing guide">{guides.map((item) => <button type="button" key={item.id} onClick={() => setGuide(item.id)} aria-pressed={guide === item.id} className={`min-h-12 shrink-0 text-sm font-semibold border-b-2 ${guide === item.id ? "border-primary text-primary" : "border-transparent text-text-muted hover:text-text"}`}>{item.label}</button>)}</div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5" aria-live="polite">
          {guide === "local" && localHouseholdRates.map((item) => <article key={item.size} className="rounded-lg border border-border p-5 sm:p-6"><p className="text-xs text-text-muted mb-2">Within a city</p><h3 className="font-display font-bold text-lg">{item.size}</h3><p className="text-primary font-bold text-xl mt-4">{item.priceRange}</p><p className="text-sm text-text-muted leading-relaxed mt-3">Confirm inventory, packing and access requirements for your home.</p><Link to={`/get-quote?service=${item.slug}&scope=local&size=${encodeURIComponent(item.size.split(" ")[0] + " BHK")}`} className="inline-flex items-center gap-2 min-h-11 text-sm font-semibold text-primary mt-3 hover:underline">Get a quote<ArrowRight size={16} aria-hidden="true" /></Link></article>)}
          {guide === "interstate" && interstateCorridors.map((item) => <article key={item.corridor} className="rounded-lg border border-border p-5 sm:p-6"><h3 className="font-display font-bold text-lg leading-snug">{item.corridor}</h3><p className="text-xs text-text-muted mt-2">Approximate distance: {item.distance}</p><dl className="space-y-3 mt-5">{[["1 BHK",item.range1BHK],["2 BHK",item.range2BHK],["3 BHK",item.range3BHK]].map(([label, range]) => <div key={label} className="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1 text-sm"><dt className="text-text-muted">{label}</dt><dd className="font-semibold">{range}</dd></div>)}</dl><p className="text-xs text-text-muted leading-relaxed mt-4">Your exact cities and inventory affect the quote.</p><Link to="/get-quote?service=home-shifting&scope=interstate" className="inline-flex items-center gap-2 min-h-11 text-primary font-semibold text-sm mt-3 hover:underline">Quote my route<ArrowRight size={16} aria-hidden="true" /></Link></article>)}
          {guide === "vehicle" && vehicleRates.map((item) => <article key={item.vehicleType} className="rounded-lg border border-border p-5 sm:p-6"><h3 className="font-display font-bold text-lg leading-snug">{item.vehicleType}</h3><dl className="space-y-3 mt-5">{[["Within a city",item.localRate],["Between states",item.interstateRate]].map(([label, range]) => <div key={label} className="text-sm"><dt className="text-text-muted mb-1">{label}</dt><dd className="font-semibold text-primary">{range}</dd></div>)}</dl><p className="text-xs text-text-muted mt-4 leading-relaxed">Confirm carrier arrangements, handover and any insurance separately.</p><Link to={`/get-quote?service=${item.slug}`} className="inline-flex items-center gap-2 min-h-11 text-primary font-semibold text-sm mt-3 hover:underline">Get a vehicle quote<ArrowRight size={16} aria-hidden="true" /></Link></article>)}
        </div>
      </div></section>
      <section className="bg-surface py-12 sm:py-16 border-y border-border" aria-labelledby="cost-factors-heading"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><h2 id="cost-factors-heading" className="font-display font-bold text-2xl sm:text-3xl tracking-tight mb-8">What shapes your final quote?</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-7">{factors.map(({icon: Icon,title,description}) => <div key={title}><Icon size={24} className="text-primary mb-3" aria-hidden="true" /><h3 className="font-bold text-base mb-2">{title}</h3><p className="text-sm text-text-muted leading-relaxed">{description}</p></div>)}</div></div></section>
      <section className="py-12 sm:py-16" aria-labelledby="quote-checklist-heading"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid lg:grid-cols-2 gap-8 lg:gap-14"><div><h2 id="quote-checklist-heading" className="font-display font-bold text-2xl sm:text-3xl tracking-tight">Make sure you know what is included</h2><p className="text-base text-text-muted leading-relaxed mt-4">Before booking, ask for a written scope and price breakdown. Review extra services and payment terms alongside the headline price.</p></div><ul className="space-y-4">{["Packing materials, loading and unloading", "Vehicle type and pickup / delivery arrangements", "Unpacking, assembly, storage or special handling", "Applicable taxes, insurance and other charges", "Payment timing, cancellation and refund terms"].map((item) => <li key={item} className="flex gap-3 text-sm sm:text-base"><Check size={18} className="text-primary shrink-0 mt-0.5" aria-hidden="true" />{item}</li>)}</ul></div></section>
      <section className="pb-12 sm:pb-16" aria-labelledby="pricing-faq-heading"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 id="pricing-faq-heading" className="font-display font-bold text-2xl sm:text-3xl tracking-tight mb-6">Questions about moving costs</h2>{questions.map(([question,answer]) => <details key={question} className="group border-b border-border"><summary className="faq-question flex items-center justify-between gap-5 min-h-16 py-4 text-sm sm:text-base font-semibold cursor-pointer hover:text-primary">{question}<span className="w-8 h-8 shrink-0 rounded-full bg-brand-soft text-primary inline-flex items-center justify-center"><Plus size={18} className="group-open:hidden" aria-hidden="true" /><Minus size={18} className="hidden group-open:block" aria-hidden="true" /></span></summary><p className="text-sm sm:text-base leading-relaxed text-text-muted pr-10 pb-5">{answer}</p></details>)}</div></section>
      <section className="pb-12 sm:pb-16" aria-labelledby="pricing-help-heading"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="rounded-lg bg-hero-overlay text-white p-6 sm:p-9 lg:p-12 flex flex-col lg:flex-row lg:items-center justify-between gap-6"><div><h2 id="pricing-help-heading" className="font-display font-bold text-2xl sm:text-3xl">Get a quote for your actual move</h2><p className="text-white/75 text-base mt-3 max-w-xl">Share your route and inventory. We will help you plan the details.</p></div><div className="flex flex-col sm:flex-row gap-3 shrink-0"><Link to={quotePath} className="inline-flex items-center justify-center min-h-12 px-6 rounded-md bg-accent hover:bg-primary text-white font-bold text-sm">Request a quote</Link><a href={`tel:${company.phone.primary.replace(/[^+\d]/g, "")}`} className="inline-flex items-center justify-center gap-2 min-h-12 px-5 rounded-md border border-white/30 hover:bg-white/10 text-white font-semibold text-sm"><PhoneCall size={17} aria-hidden="true" />Call our team</a></div></div></div></section>
    </>
  );
}
