import { useParams, Link, Navigate } from "react-router";
import { ArrowRight, ChevronRight, MapPin, PhoneCall, Check, Plus, Minus, Package, Car, Bike, Building2 } from "lucide-react";
import { allRoutes, allServiceLocations } from "../../../../data/locations/index.js";
import { getLocationPageData, locationPath } from "../../../../data/locations/pageData.js";
import { company } from "../../../../data/company";
import SEO from "../../../../configs/seo";
import NotFound from "../../shared/components/NotFound";

const domain = "https://omrudrapackersandmovers.com";
const services = [
  { name: "Home shifting", slug: "home-shifting", icon: Package, text: "Furniture, appliances and cartons. Discuss packing, dismantling and placement at your new home." },
  { name: "Office relocation", slug: "office-commercial-shifting", icon: Building2, text: "Equipment and workplace inventory. Agree on handling, building access and the moving schedule." },
  { name: "Car transport", slug: "car-transportation", icon: Car, text: "Confirm the transport method, required documents and vehicle condition records before handover." },
  { name: "Bike transport", slug: "bike-transportation", icon: Bike, text: "Discuss protective packing, collection arrangements and handover documents for your two-wheeler." },
];
export default function RoutePage() {
  const { slug: rawSlug } = useParams();
  const slug = (rawSlug || "").replace(/^route-/, "");
  const route = allRoutes.find(item => item.slug === slug);
  if (!route) return <NotFound />;
  if (rawSlug !== slug) return <Navigate to={`/route/${slug}`} replace />;
  const origin = allServiceLocations.find(item => item.slug === route.fromSlug);
  const destination = allServiceLocations.find(item => item.slug === route.toSlug);
  const originData = getLocationPageData(route.fromSlug);
  const destinationData = getLocationPageData(route.toSlug);
  const related = allRoutes.filter(item => item.fromSlug === route.fromSlug && item.slug !== slug);
  const reverse = allRoutes.find(item => item.fromSlug === route.toSlug && item.toSlug === route.fromSlug);
  const quote = service => `/get-quote?${new URLSearchParams({ from: route.from, to: route.to, scope: "interstate", ...(service ? { service } : {}) })}`;
  const canonical = `${domain}/route/${slug}`;
  const faqs = [
    [`How do I get a quote from ${route.from} to ${route.to}?`, `Use the route enquiry button to open the quote form with both cities already selected. Add your exact addresses, inventory, preferred dates and access requirements. The team will check availability and discuss your move before quoting.`],
    [`How long will my ${route.from} to ${route.to} move take?`, "Collection, loading, vehicle arrangements, road conditions and delivery access all affect the schedule. Ask the team for an expected pickup and delivery window for your dates; a city-to-city distance does not guarantee a delivery time."],
    ["What should the written quote include?", "Confirm packing, loading, transport, unloading and any unpacking or dismantling you need. Ask whether taxes, tolls, access charges, storage and insurance are included or separately priced."],
    ["Can I move a vehicle along with my household items?", "Include the vehicle details in your enquiry. Ask which transport arrangement is available, how handover is recorded and whether it can be scheduled with your household move."],
    [`Do you have an office in ${route.to}?`, "Our confirmed office is in Patna, Bihar. This route page helps you enquire about a move between these cities; collection and delivery arrangements are confirmed before booking."],
  ];
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "Service", "@id": `${canonical}#service`, name: `${route.from} to ${route.to} moving enquiries`, serviceType: "Interstate moving services", url: canonical, provider: { "@type": "Organization", name: company.legalName, url: domain }, areaServed: [route.from, route.to].map(name => ({ "@type": "Place", name })) },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: domain }, { "@type": "ListItem", position: 2, name: "Where We Serve", item: `${domain}/where-we-serve` }, { "@type": "ListItem", position: 3, name: `${route.from} to ${route.to}`, item: canonical }] },
  ] };
  return <>
    <SEO title={`${route.from} to ${route.to} Packers and Movers`} description={`Plan your move from ${route.from} to ${route.to}. Review pickup and delivery details, packing and transport options, and request a quote with your route prefilled.`} canonical={canonical} schemaJson={schema} />
    <section className="bg-surface border-b border-border py-8 sm:py-12"><div className="container mx-auto px-4 sm:px-6">
      <nav aria-label="Breadcrumb" className="flex flex-wrap gap-2 items-center text-xs sm:text-sm text-text-muted mb-7"><Link to="/">Home</Link><ChevronRight size={14} /><Link to="/where-we-serve#interstate-routes">Interstate routes</Link><ChevronRight size={14} /><span aria-current="page">{route.from} to {route.to}</span></nav>
      <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,1.2fr)_minmax(0,1fr)] gap-8 lg:gap-14 items-start">
        <div className="min-w-0"><p className="text-primary font-semibold text-sm">A PLAN FOR BOTH ENDS OF YOUR MOVE</p><h1 className="font-display font-bold text-4xl sm:text-5xl leading-tight mt-4">From {route.from}.<br /><span className="text-primary">To {route.to}.</span></h1><p className="text-text-muted text-base sm:text-lg leading-relaxed mt-5">Packers and movers for your next chapter. Plan your pickup in {route.from}{origin ? `, ${origin.state}` : ""}, and delivery in {route.to}{destination && destination.state !== route.to ? `, ${destination.state}` : ""}, with your belongings, dates and address access in mind.</p><ul className="text-sm space-y-3 mt-6">{["Your route and inventory shape the quote", "Agree on packing, handling and delivery details", "No payment to send an enquiry"].map(text => <li key={text} className="flex gap-2 items-start"><Check size={18} className="text-primary shrink-0" />{text}</li>)}</ul></div>
        <aside className="min-w-0 bg-background border border-border rounded-[var(--radius-lg)] p-5 sm:p-7"><h2 className="font-display font-bold text-2xl">Your route, ready to plan.</h2><div className="mt-6 border-l-2 border-primary/25 ml-2 pl-5 space-y-6">{[["Pickup", route.from, origin], ["Delivery", route.to, destination]].map(([label, city, place]) => <div key={label} className="relative"><MapPin size={18} className="absolute -left-[30px] top-1 text-primary bg-background" /><p className="text-xs text-text-muted">{label}</p><p className="font-semibold text-xl mt-1">{city}</p>{place && <p className="text-sm text-text-muted mt-1">{place.state}</p>}</div>)}</div><Link to={quote()} className="inline-flex justify-center items-center gap-2 w-full bg-primary text-white rounded-full px-5 py-3 font-semibold mt-7">Request this route quote<ArrowRight size={18} /></Link><p className="text-xs text-text-muted leading-relaxed mt-4">Both cities are prefilled. Add your details on the next page to send an enquiry.</p><a href={`tel:${company.phone.primary.replace(/[^+\d]/g, "")}`} className="text-primary inline-flex items-center gap-2 text-sm font-semibold min-h-11 mt-3"><PhoneCall size={17} />{company.phone.primaryDisplay}</a></aside>
      </div>
    </div></section>
    <section className="container mx-auto px-4 sm:px-6 py-10 sm:py-16"><p className="text-primary text-sm font-semibold">PICKUP AND DELIVERY MATTER EQUALLY</p><h2 className="font-display font-bold text-3xl sm:text-4xl mt-3">Two addresses. One moving plan.</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-5 mt-7">{[["Pickup in", route.from, origin, originData, "Confirm the floor, lift use, packing space, loading access and any building permissions at your current address."], ["Delivery in", route.to, destination, destinationData, "Check possession dates, unloading space, lift access and delivery hours before agreeing on a schedule."]].map(([label, city, place, data, text]) => <article key={label} className="border border-border rounded-[var(--radius-md)] p-5 sm:p-7 min-w-0"><p className="text-sm text-text-muted">{label}</p><h3 className="font-display text-2xl font-bold mt-1">{city}</h3><p className="text-sm text-text-muted leading-relaxed mt-3">{text}</p>{data?.listedAreas.length > 0 && <div className="mt-4"><p className="text-xs font-semibold text-text-muted">Include your area with the full address</p><div className="flex flex-wrap gap-2 mt-2">{data.listedAreas.slice(0, 5).map(area => <span key={area.name} className="text-xs bg-surface border border-border rounded-full px-3 py-2">{area.name}</span>)}</div></div>}{place && <Link to={locationPath(place)} className="inline-flex gap-2 items-center text-primary text-sm font-semibold min-h-11 mt-4">Explore {city} moving details<ArrowRight size={16} /></Link>}</article>)}</div></section>
    <section className="bg-surface border-y border-border py-10 sm:py-14"><div className="container mx-auto px-4 sm:px-6"><h2 className="font-display font-bold text-3xl">What are you taking to {route.to}?</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-7">{services.map(({ name, slug: serviceSlug, icon: Icon, text }) => <article key={serviceSlug} className="bg-background border border-border rounded-[var(--radius-md)] p-5"><Icon size={25} className="text-primary" /><h3 className="font-display font-bold text-xl mt-4">{name}</h3><p className="text-sm text-text-muted leading-relaxed mt-3">{text}</p><Link to={quote(serviceSlug)} className="inline-flex items-center gap-2 text-primary font-semibold text-sm min-h-11 mt-4">Enquire about this move<ArrowRight size={16} /></Link></article>)}</div></div></section>
    <section className="container mx-auto px-4 sm:px-6 py-10 sm:py-16"><h2 className="font-display font-bold text-3xl">Before your {route.from} to {route.to} move.</h2><div className="grid md:grid-cols-3 gap-6 mt-7">{[["List what travels", "Share furniture dimensions, appliance details and carton counts. Flag fragile, valuable or unusually heavy items."], ["Agree on the schedule", "Discuss pickup readiness and delivery access together. Confirm the expected transit window and how schedule changes are communicated."], ["Keep the scope in writing", "Confirm what is included, payment terms, inventory records and any insurance options before booking."]].map(([title, text]) => <article key={title} className="border-t border-border pt-5"><h3 className="font-display font-bold text-xl">{title}</h3><p className="text-sm text-text-muted leading-relaxed mt-3">{text}</p></article>)}</div><div className="bg-brand-soft border border-primary/15 rounded-[var(--radius-lg)] p-6 sm:p-8 mt-8 flex flex-col sm:flex-row gap-5 sm:items-center justify-between"><div><h3 className="font-display font-bold text-xl">What affects your route quote?</h3><p className="text-sm text-text-muted leading-relaxed mt-2 max-w-2xl">Exact addresses, inventory, packing, vehicle arrangements, dates and access determine your quote. General price ranges are indicative; confirm your own scope with the team.</p></div><Link to="/pricing" className="inline-flex gap-2 items-center text-primary font-semibold shrink-0 min-h-11">Read the pricing guide<ArrowRight size={17} /></Link></div></section>
    <section className="container mx-auto px-4 sm:px-6 pb-10 sm:pb-16"><h2 className="font-display font-bold text-3xl">Your route questions.</h2><div className="mt-6">{faqs.map(([question, answer]) => <details key={question} className="group border-b border-border"><summary className="flex items-center justify-between gap-4 py-5 font-semibold cursor-pointer list-none [&::-webkit-details-marker]:hidden">{question}<span className="text-primary shrink-0"><Plus size={20} className="group-open:hidden" /><Minus size={20} className="hidden group-open:block" /></span></summary><p className="text-text-muted leading-relaxed pb-5 max-w-3xl">{answer}</p></details>)}</div>{reverse && <Link to={`/route/${reverse.slug}`} className="inline-flex gap-2 items-center text-primary text-sm font-semibold min-h-11 mt-5">Moving the other way? {reverse.from} to {reverse.to}<ArrowRight size={16} /></Link>}{related.length > 0 && <div className="mt-8"><h3 className="font-display font-bold text-xl">Other routes from {route.from}</h3><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-4">{related.map(item => <Link key={item.slug} to={`/route/${item.slug}`} className="border border-border rounded-[var(--radius-md)] p-4 text-sm font-semibold flex justify-between items-center gap-3 hover:bg-brand-soft">{item.from} to {item.to}<ArrowRight size={16} className="text-primary shrink-0" /></Link>)}</div></div>}<div className="bg-text text-background rounded-[var(--radius-lg)] p-6 sm:p-9 mt-9 flex flex-col sm:flex-row gap-5 justify-between sm:items-center"><div><h2 className="font-display font-bold text-2xl">Next stop: {route.to}.</h2><p className="text-sm opacity-80 mt-2">Start with your route. Build the details with our team.</p></div><Link to={quote()} className="inline-flex items-center gap-2 bg-primary text-white rounded-full px-5 py-3 font-semibold shrink-0">Request this route quote<ArrowRight size={17} /></Link></div></section>
  </>;
}
