import { Link } from "react-router";
import { ArrowRight, ChevronRight, MapPin, PhoneCall, Package, Truck, Building2, Car, MessageCircle, FileText, Check, Plus, Minus } from "lucide-react";
import { company } from "../../../../data/company";
import SEO from "../../../../configs/seo";

const services = [
  { icon: Package, title: "A new home", text: "Packing, loading and transport for household moves within your city or to another destination.", href: "/services/home-shifting" },
  { icon: Building2, title: "A new workplace", text: "Discuss your office inventory, equipment, access and schedule to plan a commercial move.", href: "/services/office-commercial-shifting" },
  { icon: Car, title: "Your car or bike", text: "Share your vehicle details and route to discuss transport arrangements and preparation.", href: "/services/car-transportation" },
  { icon: Truck, title: "The support around it", text: "Explore packing, unloading and storage options to build a service plan around your needs.", href: "/services" },
];
const approach = [
  { icon: MessageCircle, title: "Start with a conversation", text: "Your route is only part of the picture. Tell us about your belongings, dates and what matters most to you." },
  { icon: Package, title: "Plan for your belongings", text: "Discuss fragile items, furniture, appliances and any special handling so packing and transport can be planned together." },
  { icon: FileText, title: "Make the details clear", text: "Review the services, price, inclusions and booking terms with the team before you agree to the move." },
];
const questions = [
  ["Where is your company based?", `Our office is in ${company.headOffice.city}, ${company.headOffice.state}. You can find the complete address below or on our Contact Us page.`],
  ["Do you help with local and interstate moves?", "You can enquire about moves within Patna and routes to other cities and states. Visit Where We Serve to explore the listed locations, then share your exact addresses to confirm availability."],
  ["Can I book only the services I need?", "Tell the team whether you need a full move or support such as packing, loading, unloading or storage. They can discuss availability and put the agreed services into your quote."],
  ["How do I begin?", "Request a quote with your pickup and destination, inventory and preferred date, or call the team to talk through your requirements."],
];

export default function About() {
  return <>
    <SEO title="About Us — Packers and Movers Based in Patna" description={`Meet ${company.legalName}, based in Patna, Bihar. Explore our approach to household, office and vehicle moving, and plan your next move with our team.`} />
    <section className="bg-surface border-b border-border py-10 sm:py-14"><div className="container mx-auto px-4 sm:px-6">
      <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-sm text-text-muted mb-7"><Link to="/" className="hover:text-primary">Home</Link><ChevronRight size={14} aria-hidden="true" /><span aria-current="page">About Us</span></nav>
      <div className="grid lg:grid-cols-2 gap-8 lg:gap-14 items-center"><div><p className="text-sm font-semibold text-primary">PATNA ROOTS. NEW BEGINNINGS.</p><h1 className="font-display font-bold text-4xl sm:text-5xl leading-tight mt-4">Behind every move,<br />there is a <span className="text-primary">new beginning.</span></h1><p className="text-text-muted text-base sm:text-lg leading-relaxed mt-5">A home, a workplace, a familiar routine. Moving means bringing what matters with you. We help you plan the practical details of getting it to your next address.</p><p className="text-sm text-text-muted mt-4">{company.legalName} · {company.headOffice.city}, {company.headOffice.state}</p><div className="flex flex-wrap gap-3 mt-7"><Link to="/get-quote" className="inline-flex gap-2 items-center bg-primary text-white rounded-full px-6 py-3 font-semibold hover:bg-primary/90">Plan your move<ArrowRight size={18} /></Link><a href={`tel:${company.phone.primary.replace(/[^+\d]/g, "")}`} className="inline-flex gap-2 items-center px-4 py-3 text-primary font-semibold hover:underline"><PhoneCall size={18} />Talk to our team</a></div></div>
      <figure className="relative"><img src="/images/services/HomeShiftingServices.webp" alt="Packing and transport for a household move" width="720" height="540" fetchPriority="high" className="w-full aspect-[4/3] object-cover rounded-[var(--radius-lg)]" /><figcaption className="bg-background border border-border rounded-[var(--radius-md)] px-5 py-4 flex items-center gap-3 relative mx-4 -mt-10 sm:mx-6"><MapPin size={24} className="text-primary shrink-0" /><span><span className="font-semibold block">At home in Patna.</span><span className="text-sm text-text-muted block mt-1">Local areas, city moves and interstate destinations.</span></span></figcaption></figure></div>
    </div></section>
    <section className="container mx-auto px-4 sm:px-6 py-10 sm:py-16"><div className="grid lg:grid-cols-[0.8fr_1.2fr] gap-6 lg:gap-16"><div><p className="text-primary text-sm font-semibold">WHO WE ARE</p><h2 className="font-display font-bold text-3xl sm:text-4xl leading-tight mt-3">A moving team.<br /><span className="text-primary">A practical approach.</span></h2></div><div className="text-text-muted leading-relaxed space-y-4"><p>{company.brandName} is based in Patna, Bihar, with services for household relocation, office shifting and vehicle transportation. We also help you discuss the packing, loading, unloading and storage needs around your move.</p><p>Every address brings different details: a narrow staircase, a lift booking, a fragile cabinet or a delivery date to work around. Sharing those details early helps the team understand the job and agree on a plan with you.</p><p>Our aim is straightforward: help you understand what your move needs, what your quote covers and what to prepare before moving day.</p></div></div></section>
    <section className="bg-surface border-y border-border py-10 sm:py-16"><div className="container mx-auto px-4 sm:px-6"><p className="text-primary text-sm font-semibold">WHAT WE HELP YOU MOVE</p><div className="flex flex-col sm:flex-row justify-between sm:items-end gap-4"><h2 className="font-display font-bold text-3xl sm:text-4xl mt-3">Different moves.<br /><span className="text-primary">One place to start.</span></h2><Link to="/services" className="inline-flex gap-2 items-center text-primary font-semibold min-h-11">Explore our services<ArrowRight size={17} /></Link></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-7">{services.map(({ icon: Icon, title, text, href }) => <article key={title} className="bg-background border border-border rounded-[var(--radius-md)] p-5 sm:p-6 flex flex-col"><Icon size={27} className="text-primary" /><h3 className="font-display font-bold text-xl mt-5">{title}</h3><p className="text-sm text-text-muted leading-relaxed mt-3 flex-1">{text}</p><Link to={href} className="inline-flex gap-2 items-center text-sm text-primary font-semibold min-h-11 mt-4">View services<ArrowRight size={16} /></Link></article>)}</div></div></section>
    <section className="container mx-auto px-4 sm:px-6 py-10 sm:py-16"><p className="text-primary text-sm font-semibold">HOW WE APPROACH YOUR MOVE</p><h2 className="font-display font-bold text-3xl sm:text-4xl mt-3">The details make <span className="text-primary">the difference.</span></h2><div className="grid md:grid-cols-3 gap-6 mt-8">{approach.map(({ icon: Icon, title, text }) => <article key={title} className="border-t border-border pt-6"><Icon size={26} className="text-primary" /><h3 className="font-display font-bold text-xl mt-4">{title}</h3><p className="text-text-muted text-sm leading-relaxed mt-3">{text}</p></article>)}</div>
      <aside className="bg-brand-soft border border-primary/15 rounded-[var(--radius-lg)] p-6 sm:p-8 lg:p-10 mt-10" aria-labelledby="quote-checklist-title">
        <div className="grid lg:grid-cols-[1fr_auto] gap-7 lg:gap-12 items-center">
          <div>
            <p className="inline-flex items-center gap-2 text-primary text-xs font-semibold uppercase tracking-wide"><FileText size={17} aria-hidden="true" />Before you book</p>
            <h3 id="quote-checklist-title" className="font-display font-bold text-2xl sm:text-3xl mt-3">A clear quote. A move you can plan.</h3>
            <p className="text-sm sm:text-base text-text-muted leading-relaxed mt-3 max-w-2xl">Know what is included before moving day. Discuss these details with our team and keep your agreed quote in writing.</p>
            <ul className="grid sm:grid-cols-2 gap-x-8 gap-y-3 mt-6 text-sm font-medium">{["Packing materials & handling", "Transport & address access", "Taxes & additional charges", "Insurance & optional services"].map(item => <li key={item} className="flex items-start gap-2.5"><Check size={17} className="text-primary shrink-0 mt-0.5" aria-hidden="true" /><span>{item}</span></li>)}</ul>
          </div>
          <div className="lg:border-l lg:border-primary/15 lg:pl-9 lg:max-w-64">
            <p className="text-sm text-text-muted leading-relaxed mb-4">Explore indicative costs and the details that affect your moving price.</p>
            <Link to="/pricing" className="inline-flex justify-center gap-3 items-center bg-primary text-white rounded-full px-5 py-3 text-sm font-semibold hover:bg-primary/90 transition-colors">See the pricing guide<ArrowRight size={17} aria-hidden="true" /></Link>
          </div>
        </div>
      </aside>
    </section>
    <section className="bg-surface border-y border-border py-10 sm:py-14"><div className="container mx-auto px-4 sm:px-6 grid lg:grid-cols-2 gap-8 lg:gap-16"><div><p className="text-primary text-sm font-semibold">OUR HOME BASE</p><h2 className="font-display font-bold text-3xl sm:text-4xl mt-3">From Patna to your<br /><span className="text-primary">next address.</span></h2><p className="text-text-muted leading-relaxed mt-4">Browse Patna neighbourhoods and the other cities, states and routes in our service directory. Tell us your exact pickup and destination so we can check the arrangements for your move.</p><Link to="/where-we-serve" className="inline-flex gap-2 items-center text-primary font-semibold min-h-11 mt-4">Find your location<ArrowRight size={17} /></Link></div><aside className="bg-background border border-border rounded-[var(--radius-lg)] p-6 sm:p-8"><MapPin size={28} className="text-primary" /><h3 className="font-display font-bold text-xl mt-4">Our Patna office</h3><address className="not-italic text-text-muted leading-relaxed mt-3">{company.headOffice.addressLine}<br />{company.headOffice.city}, {company.headOffice.state} {company.headOffice.pincode}</address><Link to="/contact" className="inline-flex gap-2 items-center text-primary font-semibold min-h-11 mt-4">Contact our team<ArrowRight size={17} /></Link></aside></div></section>
    <section className="container mx-auto px-4 sm:px-6 py-10 sm:py-16"><h2 className="font-display font-bold text-3xl">Get to know us <span className="text-primary">a little better.</span></h2><div className="mt-6">{questions.map(([question, answer]) => <details key={question} className="group border-b border-border"><summary className="flex items-center justify-between gap-4 py-5 font-semibold cursor-pointer list-none [&::-webkit-details-marker]:hidden">{question}<span className="text-primary shrink-0"><Plus size={20} className="group-open:hidden" /><Minus size={20} className="hidden group-open:block" /></span></summary><p className="text-text-muted leading-relaxed pb-5 max-w-3xl">{answer}</p></details>)}</div><div className="bg-text text-background rounded-[var(--radius-lg)] mt-10 p-6 sm:p-10 flex flex-col sm:flex-row justify-between sm:items-center gap-6"><div><h2 className="font-display font-bold text-2xl sm:text-3xl">Let’s plan your next beginning.</h2><p className="mt-2 opacity-80">Tell us where you are moving and what you want to bring.</p></div><Link to="/get-quote" className="inline-flex gap-2 items-center bg-primary text-white rounded-full px-6 py-3 font-semibold shrink-0 hover:bg-primary/90">Request a free quote<ArrowRight size={18} /></Link></div></section>
  </>;
}
