import { Link } from "react-router";
import { ChevronRight, ArrowRight, Mail, MapPin } from "lucide-react";
import { company } from "../../../../data/company";
import SEO from "../../../../configs/seo";

export default function LegalLayout({ title, description, summary, sections, email, otherPage }) {
  return <>
    <SEO title={title} description={description} />
    <section className="bg-surface border-b border-border py-9 sm:py-12"><div className="container mx-auto px-4 sm:px-6"><nav aria-label="Breadcrumb" className="flex items-center gap-2 text-sm text-text-muted mb-7"><Link to="/" className="hover:text-primary">Home</Link><ChevronRight size={14} aria-hidden="true" /><span aria-current="page">{title}</span></nav><p className="text-primary text-sm font-semibold">CLEAR INFORMATION. INFORMED DECISIONS.</p><h1 className="font-display font-bold text-4xl sm:text-5xl mt-4">{title}</h1><p className="text-text-muted text-base sm:text-lg leading-relaxed max-w-3xl mt-4">{description}</p><p className="text-sm text-text-muted mt-5">Last updated: <time dateTime="2026-10-05">5 October 2026</time></p></div></section>
    <div className="container mx-auto px-4 sm:px-6 py-8 sm:py-12 grid grid-cols-1 lg:grid-cols-[minmax(0,0.32fr)_minmax(0,1fr)] gap-8 lg:gap-14 items-start">
      <aside className="min-w-0 lg:sticky lg:top-28"><nav aria-label={`${title} contents`} className="border border-border rounded-[var(--radius-md)] p-5"><h2 className="font-semibold mb-3">On this page</h2><ol className="space-y-1">{sections.map((section, index) => <li key={section.id}><a href={`#${section.id}`} className="flex gap-2 py-2 text-sm text-text-muted hover:text-primary"><span className="text-primary w-5 shrink-0">{index + 1}.</span><span>{section.title}</span></a></li>)}</ol></nav><Link to={otherPage.href} className="inline-flex items-center gap-2 text-primary text-sm font-semibold min-h-11 mt-3">{otherPage.label}<ArrowRight size={16} /></Link></aside>
      <article className="min-w-0 max-w-3xl"><div className="bg-brand-soft border border-primary/15 rounded-[var(--radius-md)] p-5 sm:p-6 mb-8"><h2 className="font-display font-bold text-xl">At a glance</h2><ul className="mt-3 space-y-2 text-sm text-text-muted leading-relaxed list-disc pl-5">{summary.map(item => <li key={item}>{item}</li>)}</ul></div>
      {sections.map((section, index) => <section key={section.id} id={section.id} className="scroll-mt-32 border-b border-border pb-7 mb-7"><h2 className="font-display font-bold text-xl sm:text-2xl"><span className="text-primary">{index + 1}.</span> {section.title}</h2><div className="mt-4 space-y-4 text-text-muted text-sm sm:text-base leading-relaxed">{section.paragraphs.map(text => <p key={text}>{text}</p>)}{section.items && <ul className="list-disc pl-5 space-y-2">{section.items.map(text => <li key={text}>{text}</li>)}</ul>}</div></section>)}
      <section className="bg-surface border border-border rounded-[var(--radius-lg)] p-6 sm:p-8"><h2 className="font-display font-bold text-2xl">Questions about this policy?</h2><p className="text-text-muted text-sm leading-relaxed mt-3">Contact {company.legalName}. Include your name and enquiry or booking reference, if relevant.</p><a href={`mailto:${email}`} className="flex items-start gap-2 text-primary font-semibold text-sm py-3 mt-2"><Mail size={18} className="shrink-0" /><span className="break-all">{email}</span></a><address className="not-italic flex items-start gap-2 text-sm text-text-muted leading-relaxed"><MapPin size={18} className="shrink-0 mt-1" /><span>{company.headOffice.addressLine}, {company.headOffice.city}, {company.headOffice.state} {company.headOffice.pincode}</span></address><Link to="/contact" className="inline-flex gap-2 items-center text-primary font-semibold text-sm min-h-11 mt-3">Contact our team<ArrowRight size={16} /></Link></section>
      </article>
    </div>
  </>;
}
