import { company } from "../../../../data/company";
import LegalLayout from "./LegalLayout";

const sections = [
  { id: "scope", title: "Who this policy covers", paragraphs: [`This policy describes how ${company.legalName}, based in Patna, Bihar, handles personal information when you use this website, contact our team or enquire about moving services.`, "It covers website enquiries and the information you provide while discussing or arranging a move. External services such as WhatsApp and Google Maps have their own privacy policies."] },
  { id: "collection", title: "Information we collect", paragraphs: ["The information collected depends on the form or service you use. Please provide only what is needed for your enquiry and avoid including passwords, payment card details or unrelated sensitive information."], items: ["Contact details: your name, phone number and email address. Email is required on the general contact form and may be optional on other enquiry forms.", "Moving details: pickup and destination, service type, preferred timing, home or move size, and inventory or access details you share with the team.", "Enquiry and booking information: your selected subject, message, booking reference, correspondence and documents you provide for your move.", "Technical information: network address, approximate location derived from your connection, browser and request information used by hosting and security services."] },
  { id: "use", title: "How we use your information", paragraphs: ["We use your information to respond to questions, prepare quotes, discuss availability, coordinate requested services, manage bookings and resolve support enquiries. We also use relevant records for accounting, security, fraud prevention and legal obligations.", "Sending an enquiry allows us to contact you about that enquiry using the details you provide. You can ask us to stop optional communications. We do not treat a quote request as permission for unrelated marketing."] },
  { id: "location", title: "Location detection and browser storage", paragraphs: ["The website may suggest a city using approximate network-location information supplied by our hosting provider. You can change this suggestion or enter an address yourself.", "If you choose to detect your location, your browser asks for permission before sharing GPS coordinates. Coordinates are sent to OpenStreetMap’s Nominatim service to identify the nearby city. You can decline permission and type your location instead.", "Recent search terms are saved in local storage on your device. Approximate city suggestions may be cached in session storage for your browsing session. You can clear this information using the website’s search controls where available or your browser’s site-data settings. This storage does not automatically save your complete enquiry form."] },
  { id: "cookies", title: "Cookies and planned website analytics", paragraphs: ["Google Analytics 4 (GA4) is not currently installed on this website. We plan to introduce it to understand site usage, such as pages visited, navigation and engagement, and to improve the website.", "Cookies are small files stored by your browser. They are different from the local and session storage described above. Our current site uses that browser storage for recent searches and city suggestions; it does not currently set GA4 analytics cookies. Hosting or security services may use their own cookies where needed to operate or protect the website.", "When GA4 is introduced, this policy will be updated to describe its actual configuration, cookies, data use and available choices. Optional analytics will be introduced with appropriate consent controls. No analytics consent banner is currently active.", "GA4 can use first-party cookies such as _ga and _ga_<identifier> to distinguish visitors and sessions. Their duration depends on the configuration used. We will confirm the cookies and retention settings when analytics is enabled, rather than treating planned settings as current practice.", "Names, phone numbers, email addresses, full moving addresses and enquiry messages must not be included in analytics events or page URLs sent to Google. You can also manage or clear cookies through your browser’s settings."] },
  { id: "sharing", title: "Service providers and external links", paragraphs: ["Website enquiries are stored through our Cloudflare-hosted application and database. Configured email notifications are handled through Brevo. Cloudflare may also process technical information for hosting and anti-bot checks. Providers may process information outside India under their own service arrangements.", "Where needed to arrange your requested move, relevant contact, route and inventory details may be shared with people carrying out the agreed services. Information may also be disclosed when required by law or to address a legal claim.", "Opening a WhatsApp link transfers you to WhatsApp; enquiry details may be included in a prepared message, which you choose to send. Google Maps links open an external map search. Those services handle information under their own policies. We do not sell your enquiry information."] },
  { id: "retention", title: "Security and retention", paragraphs: ["We use technical and organisational measures intended to restrict unauthorised access. No online service can guarantee complete security. Avoid sending information that is not needed for your enquiry.", "Records are kept while needed to respond to enquiries, provide services, maintain business records, resolve disputes or meet applicable legal requirements. Retention depends on the type of record and purpose. This policy does not promise automatic deletion after a fixed number of days."] },
  { id: "choices", title: "Your choices and privacy requests", paragraphs: ["You can contact us to request access to the information you provided, correct inaccuracies, request deletion, withdraw permission for optional processing or raise a privacy concern. Please explain your request and include details that help us identify the relevant enquiry or booking.", "We may need to verify your identity before responding. Requests are handled subject to applicable law and any records we must retain. Withdrawing permission for information essential to an enquiry or service may affect our ability to continue it.", "Our services and enquiry forms are intended for adults. Please do not submit children’s personal information unless it is necessary for a service and you are authorised to provide it."] },
  { id: "changes", title: "Policy updates and concerns", paragraphs: ["We may update this policy when website features, service arrangements or applicable requirements change. The date above identifies the latest revision.", `For privacy questions or complaints, email ${company.email.privacy}. Describe your concern and the relevant enquiry or booking so the team can review it. This contact route does not limit any rights or remedies available under applicable law.`] },
];
export default function Privacy() {
  return <LegalLayout title="Privacy Policy" description="Understand what information you share with us, how it is used and how to contact us about your privacy." summary={["Your details help us respond to enquiries and plan requested services.", "Location detection is optional; you can enter your city yourself.", "GA4 analytics is planned and is not currently active.", "You can contact us to correct information or raise a privacy request."]} sections={sections} email={company.email.privacy} otherPage={{ href: "/terms", label: "Read Terms of Service" }} />;
}
