import { company } from "../../../../data/company";
import LegalLayout from "./LegalLayout";

const sections = [
  { id: "scope", title: "Website and service enquiries", paragraphs: [`These terms describe the use of this website and enquiries for moving services offered by ${company.legalName}, based in Patna, Bihar.`, "Submitting a form, viewing a price estimate or starting a WhatsApp conversation does not confirm a booking, reserve a vehicle or create a final moving quote. A booking requires the team to confirm availability and the agreed service details with you.", "For a confirmed move, read these terms together with your written quote, booking confirmation and any applicable consignment or insurance documents. Specific arrangements should be agreed before work begins. Nothing here overrides rights that cannot be excluded under applicable law."] },
  { id: "quotes", title: "Estimates, quotes and service scope", paragraphs: ["Prices and ranges displayed on the website are indicative planning estimates. The final quote depends on your inventory, route, packing needs, dates, address access and selected services.", "Before booking, confirm the service inclusions and exclusions, applicable taxes, extra charges, quotation validity and any survey requirements. Do not assume that packing, unpacking, assembly, storage or insurance is included unless it is listed in the agreed quote.", "Tell the team if your inventory, route, date or access arrangements change. Any effect on the price or service plan should be discussed and agreed before the changed work proceeds."] },
  { id: "responsibilities", title: "Information and preparation", paragraphs: ["Provide accurate contact details, addresses, inventory and scheduling information. You must be authorised to arrange the movement of the goods and to provide information about anyone else involved in the booking."], items: ["Disclose fragile, high-value, unusually heavy or oversized items and any special handling needs.", "Explain floors, lift availability, stairs, parking, vehicle access and building entry restrictions at both addresses.", "Arrange permissions and prepare appliances or personal items as agreed with the team.", "Keep essential documents, cash, jewellery and other personal valuables with you unless a specific arrangement is accepted in writing."] },
  { id: "goods", title: "Restricted items and vehicle transport", paragraphs: ["Do not include illegal goods, explosives, flammable or hazardous materials, leaking containers or other items that cannot be safely or lawfully transported. Ask the team before including perishables, plants, animals or items requiring special permits.", "For car or bike transportation, confirm preparation instructions, required documents, pickup and delivery arrangements and the condition-recording process before handover. Remove personal belongings unless the team expressly agrees otherwise."] },
  { id: "payment", title: "Payment and booking confirmation", paragraphs: ["Request the payment schedule, any advance amount, accepted payment method and invoice details before making a payment. The agreed booking documents should identify when payments are due and what they cover.", "An online enquiry is free to submit. It does not authorise a payment or guarantee that your requested date is available. Use the company’s confirmed payment instructions and contact the team if you receive conflicting details."] },
  { id: "changes", title: "Rescheduling, cancellation and refunds", paragraphs: ["Contact the team as soon as you need to change or cancel a booking. Availability, work already performed and costs already incurred may affect the arrangements.", "Ask for the applicable rescheduling, cancellation and refund conditions in writing before booking. These pages do not establish a universal cancellation fee, refund percentage or processing deadline. Any charge or deduction must follow the agreed terms and applicable law.", "If the company cannot provide an agreed service, contact the team to discuss an alternative arrangement and any refund due under the booking terms and applicable law."] },
  { id: "delivery", title: "Pickup, transit and delivery", paragraphs: ["Pickup and delivery plans are agreed with the team. Travel conditions, weather, access restrictions and other practical factors can affect timing. Any date or delivery commitment should be confirmed in your booking documents.", "Inspect your goods and record visible damage or missing items when practical at delivery. Keep inventory records, photographs and booking documents, and report concerns to the team promptly. Signing a delivery record does not remove rights that cannot be excluded by law."] },
  { id: "insurance", title: "Insurance, damage and claims", paragraphs: ["Transit insurance is not automatically included in a website estimate. If you request insurance, confirm the provider, premium, insured value, coverage, exclusions and claim requirements before booking.", "Report loss or damage with your booking reference, item details and available evidence. Insurer procedures and deadlines depend on the applicable policy. Any company responsibility is determined by the agreed service, facts and applicable law; this page does not create a blanket liability waiver or arbitrary compensation limit."] },
  { id: "website", title: "Website use and personal information", paragraphs: ["Use the website lawfully. Do not submit false enquiries, attempt unauthorised access or interfere with the website or other users. External links and services operate under their own terms.", "The Privacy Policy explains the handling of enquiry information, browser storage, location detection and external services. Contact us if you need help correcting information you submitted."] },
  { id: "concerns", title: "Concerns, applicable law and updates", paragraphs: [`For a service concern, contact ${company.email.legal} or use our Contact Us page. Include your booking reference, route, concern and supporting details so the team can review the matter.`, "These terms are governed by applicable Indian law. Nothing in these terms prevents you from using consumer remedies, complaint processes or other rights available under applicable law. Disputes may be brought before the legally competent authority or forum.", "Updates to this page are identified by the date above. Changes do not automatically alter the agreed terms of an existing booking; any change to that booking should be separately discussed and agreed."] },
];
export default function Terms() {
  return <LegalLayout title="Terms of Service" description="Know how enquiries, quotes and bookings work, and what to confirm before arranging your move." summary={["A website enquiry is not a confirmed booking or final price.", "Agree the service scope, payment and cancellation terms in writing.", "Insurance is subject to the policy you choose; your statutory rights remain protected."]} sections={sections} email={company.email.legal} otherPage={{ href: "/privacy", label: "Read Privacy Policy" }} />;
}
