import { useState } from "react";
import { Link } from "react-router";
import { ArrowRight, ChevronRight, Search, X, Check, Plus, Minus, PhoneCall, Package, MapPin, CalendarDays, Building2 } from "lucide-react";
import SEO from "../../../../configs/seo";
import { company } from "../../../../data/company";
import CustomSelect from "../../shared/components/CustomSelect";
import HowItWorks from "../Home/components/HowItWorks";

import { services } from "../../../../data/services";

const categories = [{ id: "all", label: "All services" }, { id: "home", label: "Home & office" }, { id: "vehicle", label: "Vehicles" }, { id: "support", label: "Packing & support" }];
const factors = [
  { icon: Package, title: "What you are moving", text: "Item count, size, weight and any fragile or special-care goods." },
  { icon: MapPin, title: "Your route", text: "Pickup and delivery locations, distance and transport requirements." },
  { icon: Building2, title: "Access at both addresses", text: "Floor, stairs, lift availability and space for loading." },
  { icon: CalendarDays, title: "Timing and extras", text: "Your moving date, packing, storage and any additional services." },
];
const questions = [
  { question: "Can I book only packing or loading support?", answer: "You can enquire about packing, unpacking, loading or unloading separately. Share your inventory, access details and any transport you have already arranged so the team can confirm the scope." },
  { question: "How do I get a quote for my service?", answer: "Choose a service and send your route, inventory and preferred date through the quote form. The team will discuss the details with you. Confirm the price, included services and any additional charges before booking." },
  { question: "Will my goods travel in a dedicated vehicle?", answer: "Vehicle arrangements depend on your inventory, route and availability. Ask which transport option is proposed, whether the load is shared, and how pickup and delivery will be handled before booking." },
  { question: "Is transit insurance included?", answer: "Insurance terms vary by the proposed policy and service. Confirm availability, premium, declared value, coverage, exclusions and claim requirements with the team before agreeing to cover." },
  { question: "What should I share about fragile or valuable items?", answer: "Mention fragile items, artwork, electronics and anything requiring special handling during the enquiry. Ask which packing materials and handling arrangements are included in your quote." },
];

export default function ServicesPage() {
  const [category, setCategory] = useState("all");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState("");
  const visible = services.filter((service) => (category === "all" || service.category === category) && `${service.title} ${service.description} ${service.points.join(" ")}`.toLowerCase().includes(query.trim().toLowerCase()));
  const selectedService = services.find((service) => service.title === selected);
  const quotePath = selectedService ? `/get-quote?service=${selectedService.slug}` : "/get-quote";
  return (
    <>
      <SEO title="Moving, Packing & Transport Services" description="Explore home and office relocation, vehicle transport, packing, loading and storage with Om Rudra. Choose a service and request a quote for your move." />
      <section className="bg-brand-soft/50 border-b border-border py-8 sm:py-12 lg:py-14" aria-labelledby="services-page-heading">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <nav aria-label="Breadcrumb" className="mb-6"><ol className="flex items-center gap-2 text-sm text-text-muted"><li><Link to="/" className="inline-flex min-h-11 items-center hover:text-primary">Home</Link></li><li aria-hidden="true"><ChevronRight size={14} /></li><li aria-current="page">Services</li></ol></nav>
          <div className="grid lg:grid-cols-[1.3fr_1fr] gap-8 lg:gap-14 items-center">
            <div><p className="text-primary text-sm font-semibold mb-3">Home, office and vehicle moves</p><h1 id="services-page-heading" className="font-display font-extrabold text-[clamp(2rem,4vw,3.5rem)] leading-[1.12] tracking-tight max-w-2xl">The right help.<br /><span className="text-primary">For your next move.</span></h1><p className="text-text-muted text-base sm:text-lg leading-relaxed max-w-xl mt-5">A complete relocation or support with just one part. Choose what you need and plan the details with our team.</p><a href="#service-catalogue" className="inline-flex items-center gap-2 min-h-11 mt-5 text-sm font-semibold text-primary hover:underline">Explore services<ArrowRight size={17} aria-hidden="true" /></a></div>
            <div className="rounded-lg bg-background border border-border p-5 sm:p-7 shadow-card"><h2 className="font-display font-bold text-xl mb-2">What can we help you move?</h2><p className="text-sm text-text-muted mb-5">Start with a service. Add your route and moving details next.</p><CustomSelect id="service-quote-choice" label="Choose your service" value={selected} onChange={setSelected} options={services.map((service) => service.title)} placeholder="Select a moving service" /><Link to={quotePath} className="mt-4 w-full inline-flex items-center justify-center gap-2 min-h-12 bg-accent hover:bg-primary text-white rounded-md text-sm font-bold transition-colors">Get a free quote<ArrowRight size={17} aria-hidden="true" /></Link><a href={`tel:${company.phone.primary.replace(/[^+\d]/g, "")}`} className="flex items-center justify-center gap-2 min-h-11 mt-2 text-sm text-text-muted hover:text-primary"><PhoneCall size={16} aria-hidden="true" />Or talk to our team</a></div>
          </div>
        </div>
      </section>
      <section id="service-catalogue" className="py-12 sm:py-16 scroll-mt-5" aria-labelledby="service-catalogue-heading">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-5 mb-6"><div><h2 id="service-catalogue-heading" className="font-display font-bold text-2xl sm:text-3xl tracking-tight">Choose your service</h2><p className="text-sm sm:text-base text-text-muted mt-2">Explore the options and what to discuss before booking.</p></div><div className="relative w-full sm:w-72"><label htmlFor="service-search" className="sr-only">Search services</label><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted" size={18} aria-hidden="true" /><input id="service-search" type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search services" className="w-full min-h-12 pl-10 pr-10 border border-border rounded-md text-base bg-background" />{query && <button type="button" onClick={() => setQuery("")} aria-label="Clear service search" className="absolute right-0 top-0 w-11 h-12 flex items-center justify-center text-text-muted"><X size={16} /></button>}</div></div>
          <div className="flex gap-5 sm:gap-8 overflow-x-auto border-b border-border mb-5" aria-label="Filter services">{categories.map((item) => <button type="button" key={item.id} onClick={() => setCategory(item.id)} aria-pressed={category === item.id} className={`min-h-12 shrink-0 text-sm font-semibold border-b-2 ${category === item.id ? "text-primary border-primary" : "text-text-muted border-transparent hover:text-text"}`}>{item.label}</button>)}</div>
          <p className="text-xs text-text-muted mb-6" role="status">{visible.length} {visible.length === 1 ? "service" : "services"}{query.trim() ? ` matching “${query.trim()}”` : " to explore"}</p>
          {visible.length ? <ul className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-7">{visible.map((service) => <li key={service.slug} className="rounded-lg border border-border overflow-hidden bg-background flex flex-col"><Link to={`/services/${service.slug}`} className="block overflow-hidden bg-surface"><img src={`/images/services/${service.image}`} alt={service.title} loading="lazy" width="640" height="400" className="w-full aspect-[16/9] object-cover" /></Link><div className="p-5 sm:p-6 flex flex-col flex-1"><h3 className="font-display font-bold text-xl"><Link to={`/services/${service.slug}`} className="hover:text-primary">{service.title}</Link></h3><p className="text-sm text-text-muted leading-relaxed mt-2 mb-4">{service.description}</p><ul className="space-y-2 mb-5 flex-1">{service.points.map((point) => <li key={point} className="flex gap-2 text-sm"><Check size={16} className="text-primary shrink-0 mt-0.5" aria-hidden="true" />{point}</li>)}</ul><div className="flex flex-wrap items-center justify-between gap-x-3 border-t border-border pt-2"><Link to={`/services/${service.slug}`} className="inline-flex items-center min-h-11 text-sm font-semibold hover:text-primary">View service</Link><Link to={`/get-quote?service=${service.slug}`} className="inline-flex items-center gap-2 min-h-11 text-sm font-semibold text-primary hover:underline">Get a quote<ArrowRight size={16} aria-hidden="true" /></Link></div></div></li>)}</ul> : <div className="rounded-lg bg-surface p-8 text-center"><h3 className="font-bold text-lg">No services match your search</h3><p className="text-sm text-text-muted mt-2">Try another term or browse all services.</p><button type="button" onClick={() => { setQuery(""); setCategory("all"); }} className="min-h-11 mt-4 px-5 bg-primary text-white rounded-md text-sm font-semibold">Reset filters</button></div>}
        </div>
      </section>
      <section className="bg-surface py-12 sm:py-16 border-y border-border" aria-labelledby="service-cost-heading"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-2xl mb-8"><h2 id="service-cost-heading" className="font-display font-bold text-2xl sm:text-3xl tracking-tight">A quote built around your move</h2><p className="text-text-muted text-base leading-relaxed mt-3">Your service, inventory and route shape the price. Share these details so the team can assess what you need.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">{factors.map(({icon: Icon, title, text}) => <div key={title}><Icon size={24} className="text-primary mb-3" aria-hidden="true" /><h3 className="font-bold text-base mb-2">{title}</h3><p className="text-sm text-text-muted leading-relaxed">{text}</p></div>)}</div><Link to="/pricing" className="inline-flex items-center gap-2 min-h-11 text-primary font-semibold text-sm mt-6 hover:underline">Understand moving costs<ArrowRight size={16} aria-hidden="true" /></Link></div></section>
      <HowItWorks />
      <section className="py-12 sm:py-16" aria-labelledby="service-faq-heading"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 id="service-faq-heading" className="font-display font-bold text-2xl sm:text-3xl mb-6 tracking-tight">Questions before you book</h2>{questions.map((faq) => <details key={faq.question} className="group border-b border-border"><summary className="faq-question flex items-center justify-between gap-5 cursor-pointer min-h-16 py-4 text-sm sm:text-base font-semibold hover:text-primary">{faq.question}<span className="shrink-0 w-8 h-8 rounded-full bg-brand-soft text-primary inline-flex items-center justify-center"><Plus size={18} className="group-open:hidden" aria-hidden="true" /><Minus size={18} className="hidden group-open:block" aria-hidden="true" /></span></summary><p className="text-sm sm:text-base leading-relaxed text-text-muted pb-5 pr-10">{faq.answer}</p></details>)}</div></section>
      <section className="pb-12 sm:pb-16" aria-labelledby="service-help-heading"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="bg-hero-overlay text-white rounded-lg p-6 sm:p-9 lg:p-12 flex flex-col lg:flex-row lg:items-center justify-between gap-6"><div><h2 id="service-help-heading" className="font-display font-bold text-2xl sm:text-3xl">Not sure which service fits?</h2><p className="text-white/75 text-base mt-3 max-w-xl">Tell us what you are moving. Our team will help you work through the options.</p></div><div className="flex flex-col sm:flex-row gap-3 shrink-0"><Link to="/get-quote" className="inline-flex justify-center items-center min-h-12 px-6 bg-accent hover:bg-primary text-white rounded-md font-bold text-sm">Plan my move</Link><a href={`tel:${company.phone.primary.replace(/[^+\d]/g, "")}`} className="inline-flex justify-center items-center gap-2 min-h-12 px-5 border border-white/30 rounded-md text-sm font-semibold hover:bg-white/10"><PhoneCall size={17} aria-hidden="true" />Call our team</a></div></div></div></section>
    </>
  );
}
