import { useParams, Link } from "react-router";
import { responsiveImageSet } from "../../../../utils/responsiveImages";
import NotFound from "../../shared/components/NotFound";
import { ChevronRight, ArrowRight, Check, Plus, Minus, PhoneCall } from "lucide-react";
import { company } from "../../../../data/company";
import { services } from "../../../../data/services";
import { serviceDetails } from "../../../../data/serviceDetails";
import RouteEnquiryBar from "../Home/components/RouteEnquiryBar";
import SEO from "../../../../configs/seo";

export default function ServiceDetail() {
  const { slug } = useParams();
  const service = services.find((item) => item.slug === slug);
  const detail = serviceDetails[slug];
  if (!service || !detail) return <NotFound />;
  const related = services.filter((item) => item.slug !== slug).sort((a, b) => {
    const score = (item) => item.category === service.category ? 0 : item.slug === "goods-insurance" ? 1 : item.category === "support" ? 2 : 3;
    return score(a) - score(b);
  }).slice(0, 3);
  const steps = [
    { title: "Share your requirements", text: "Tell us your route, inventory and preferred date. Include any special handling or access needs." },
    { title: "Review the proposal", text: "Discuss the recommended arrangements. Confirm scope, availability, pricing and any additional charges." },
    { title: slug === "goods-insurance" ? "Confirm policy documents" : "Agree on the plan", text: slug === "goods-insurance" ? "Read the policy wording and confirm coverage, exclusions and documents before agreeing to cover." : "Agree on the schedule, responsibilities and handover details before the service begins." },
  ];
  return (
    <>
      <SEO title={`${service.title} Services`} description={detail.intro} />
      <section className="bg-brand-soft/50 pt-5 sm:pt-8" aria-labelledby="service-detail-heading">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <nav aria-label="Breadcrumb" className="mb-5 sm:mb-7"><ol className="flex flex-wrap items-center gap-2 text-xs sm:text-sm text-text-muted"><li><Link to="/" className="inline-flex min-h-11 items-center hover:text-primary">Home</Link></li><li aria-hidden="true"><ChevronRight size={13} /></li><li><Link to="/services" className="inline-flex min-h-11 items-center hover:text-primary">Services</Link></li><li aria-hidden="true"><ChevronRight size={13} /></li><li aria-current="page">{service.title}</li></ol></nav>
          <div className="grid sm:grid-cols-2 gap-7 lg:gap-12 items-center pb-8 sm:pb-10">
            <div><p className="text-sm font-semibold text-primary mb-3">{detail.eyebrow}</p><h1 id="service-detail-heading" className="font-display font-extrabold text-[clamp(2rem,3.7vw,3.25rem)] leading-[1.13] tracking-tight">{detail.headline}</h1><p className="text-base sm:text-lg text-text-muted leading-relaxed mt-4 max-w-xl">{detail.intro}</p><a href="#quote-form-section" className="inline-flex items-center gap-2 min-h-11 mt-4 text-sm font-semibold text-primary hover:underline">Request your quote<ArrowRight size={17} aria-hidden="true" /></a></div>
            <img src={`/images/services/${service.image}`} srcSet={responsiveImageSet(`/images/services/${service.image}`)} sizes="(min-width: 1024px) 400px, (min-width: 640px) 50vw, 100vw" alt={service.title} width="720" height="480" fetchPriority="high" className="hidden sm:block w-full aspect-[3/2] max-h-80 object-cover rounded-lg" />
          </div>
        </div>
        <RouteEnquiryBar key={slug} defaultService={detail.enquiry} />
      </section>
      <section className="py-12 sm:py-16" aria-labelledby="service-scope-heading"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid lg:grid-cols-[1.2fr_1fr] gap-8 lg:gap-14"><div><h2 id="service-scope-heading" className="font-display font-bold text-2xl sm:text-3xl tracking-tight">Plan the service around your needs</h2><p className="text-base text-text-muted leading-relaxed mt-4 max-w-2xl">{detail.overview}</p><h3 className="text-base font-bold mt-6 mb-4">What to discuss with the team</h3><ul className="space-y-3">{service.points.map((point) => <li key={point} className="flex gap-3 text-sm sm:text-base"><Check size={18} className="text-primary shrink-0 mt-0.5" aria-hidden="true" />{point}</li>)}</ul></div><aside className="rounded-lg bg-surface border border-border p-5 sm:p-7 self-start" aria-labelledby="service-prepare-heading"><p className="text-xs uppercase tracking-wider text-primary font-semibold mb-3">Before you enquire</p><h2 id="service-prepare-heading" className="font-display font-bold text-xl mb-5">A little preparation helps</h2><ul className="space-y-4">{detail.prepare.map((item) => <li key={item} className="flex gap-3 text-sm leading-relaxed"><span className="w-1.5 h-1.5 rounded-full bg-primary shrink-0 mt-2" aria-hidden="true" />{item}</li>)}</ul></aside></div></section>
      <section className="bg-surface py-12 sm:py-16 border-y border-border" aria-labelledby="service-plan-heading"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><h2 id="service-plan-heading" className="font-display font-bold text-2xl sm:text-3xl tracking-tight mb-8">From enquiry to an agreed plan</h2><ol className="grid sm:grid-cols-3 gap-7 sm:gap-8">{steps.map((step, index) => <li key={step.title} className="flex sm:block gap-4"><span className="flex items-center justify-center w-9 h-9 rounded-full bg-primary text-white text-sm font-bold shrink-0 sm:mb-4">{index + 1}</span><div><h3 className="font-bold text-base mb-2">{step.title}</h3><p className="text-sm text-text-muted leading-relaxed">{step.text}</p></div></li>)}</ol></div></section>
      <section className="py-12 sm:py-16" aria-labelledby="service-detail-faq-heading"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 id="service-detail-faq-heading" className="font-display font-bold text-2xl sm:text-3xl tracking-tight mb-6">Questions about {service.title.toLowerCase()}</h2>{detail.questions.map(([question, answer]) => <details key={question} className="group border-b border-border"><summary className="faq-question flex items-center justify-between gap-5 min-h-16 py-4 text-sm sm:text-base font-semibold cursor-pointer hover:text-primary">{question}<span className="w-8 h-8 shrink-0 rounded-full bg-brand-soft text-primary inline-flex items-center justify-center"><Plus size={18} className="group-open:hidden" aria-hidden="true" /><Minus size={18} className="hidden group-open:block" aria-hidden="true" /></span></summary><p className="text-sm sm:text-base text-text-muted leading-relaxed pb-5 pr-10">{answer}</p></details>)}</div></section>
      <section className="pb-12 sm:pb-16" aria-labelledby="related-services-heading"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex items-center justify-between gap-4 mb-6"><h2 id="related-services-heading" className="font-display font-bold text-2xl sm:text-3xl tracking-tight">You may also need</h2><Link to="/services" className="inline-flex items-center gap-2 min-h-11 text-primary font-semibold text-sm shrink-0 hover:underline">All services<ArrowRight size={16} aria-hidden="true" /></Link></div><ul className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{related.map((item) => <li key={item.slug}><Link to={`/services/${item.slug}`} className="block rounded-lg overflow-hidden border border-border bg-background hover:border-primary/40 transition-colors"><img src={`/images/services/${item.image}`} srcSet={responsiveImageSet(`/images/services/${item.image}`)} sizes="(min-width: 1024px) 400px, (min-width: 640px) 50vw, 100vw" alt="" loading="lazy" width="640" height="360" className="w-full aspect-[16/9] object-cover" /><div className="p-5"><h3 className="font-display font-bold text-lg mb-2">{item.title}</h3><p className="text-sm text-text-muted leading-relaxed">{item.description}</p><span className="inline-flex gap-2 items-center min-h-11 text-primary font-semibold text-sm mt-2">Explore service<ArrowRight size={16} aria-hidden="true" /></span></div></Link></li>)}</ul></div></section>
      <section className="pb-12 sm:pb-16" aria-labelledby="service-detail-help-heading"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="rounded-lg bg-hero-overlay text-white p-6 sm:p-9 flex flex-col lg:flex-row lg:items-center justify-between gap-6"><div><h2 id="service-detail-help-heading" className="font-display font-bold text-2xl">Have a specific requirement?</h2><p className="text-white/75 text-base mt-3">Discuss the details with our moving team before you book.</p></div><div className="flex flex-col sm:flex-row gap-3"><a href="#quote-form-section" className="inline-flex items-center justify-center min-h-12 px-6 rounded-md bg-accent hover:bg-primary text-white font-bold text-sm">Request a quote</a><a href={`tel:${company.phone.primary.replace(/[^+\d]/g, "")}`} className="inline-flex items-center justify-center min-h-12 px-5 gap-2 rounded-md border border-white/30 hover:bg-white/10 text-white font-semibold text-sm"><PhoneCall size={17} aria-hidden="true" />Call our team</a></div></div></div></section>
    </>
  );
}
